feat: [DCS-220] add count_usa_phone and percent_usa_phone functions #220
datachecks/datachecks pull request #221
Opened 2024-08-20 04:13 UTC by ashank2603

### Fixes/Implements #

## Description

Validity function for `count_usa_phone` and `percent_usa_phone`

## Type of change

Delete irrelevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

- [x] Locally Tested
- [ ] Needs Testing From Production

2024-08-20 05:47 UTC, WeryZebra-Yue requested changes

2024-08-20 05:47 UTC, WeryZebra-Yue commented on datachecks/core/validation/validity_validation.py
> +            valid_count, total_count = self.data_source.query_string_pattern_validity(
Check if we need total_count or you can remove it @ashank2603

2024-08-20 05:47 UTC, WeryZebra-Yue commented on datachecks/core/datasource/sql_datasource.py
>      regex_pattern = {
move this into the function @ashank2603

2024-08-20 05:50 UTC, WeryZebra-Yue commented on datachecks/core/datasource/sql_datasource.py
>      regex_pattern = {
@ashank2603  Please create the same for SEARCH Datasource

2024-08-21 06:07 UTC, Ryuk-me commented
Missing test cases for configuration parser @ashank2603 
please add it in `tests/core/configuration/test_configuration_v1.py`

2024-08-21 10:35 UTC, subhankarb approved these changes

2024-08-21 12:46 UTC, merged